[package]
name = "zookeeper"
version = "0.5.9"
authors = ["Nandor Kracser <bonifaido@gmail.com>"]
license = "MIT"
homepage = "https://github.com/bonifaido/rust-zookeeper"
repository = "https://github.com/bonifaido/rust-zookeeper"
documentation = "http://bonifaido.github.io/rust-zookeeper"
description = "A minimal ZooKeeper client"
readme = "README.md"
keywords = ["zk", "zookeeper", "distributed", "coordination"]
edition = "2018"

[dependencies]
async-trait = "0.1"
byteorder = "1.2"
bytes = "0.5"
futures = "0.3"
lazy_static = "1.0"
log = "0.4"
tokio = { version = "0.2", features = ["rt-threaded", "sync", "tcp", "time", "io-util", "macros"] }
snowflake = "1.0.0"
zookeeper_derive = { path = "zookeeper-derive", version = "0.4.1" }

[dev-dependencies]
env_logger = "0.7"

[features]
unstable = []
